variables:
    GIT_SSL_NO_VERIFY: "true"
before_script:
#  - cd frontend
#  - npm install
frontend:
  image: node:6.6.0
  script:
    - export PATH=$PATH:node_modules/.bin
    - npm install
    - bower install --allow-root
    - npm run test
    - npm run build
#backend:
#  image: maven:3.3.9-jdk-8
#  script:
#    - cd backend
#    - mvn package
