variables:
    GIT_SSL_NO_VERIFY: "true"
before_script:
    - export PATH=$PATH:node_modules/.bin
    - npm install --unsafe-perm
unit_test:
  image: node:6.6.0
  stage: test
  script:
    - npm run test-single
