export class NoosferoKnownEvents {
    IMAGE_PROFILE_UPDATED = 'IMAGE_PROFILE_UPDATED';
    PROFILE_INFO_UPDATED = 'PROFILE_INFO_UPDATED';
    ARTICLE_UPDATED = 'ARTICLE_UPDATED';
    TASK_CLOSED = 'TASK_CLOSED';
    BLOCK_CHANGED = 'BLOCK_CHANGED';
    BLOCKS_SAVED = 'BLOCKS_SAVED';
    PROFILE_MEMBERSHIP_CHANGED = 'PROFILE_MEMBERSHIP_CHANGED';
    PROFILE_FRIENDSHIP_CHANGED = 'PROFILE_FRIENDSHIP_CHANGED';
    ARTICLE_SAVE_ERROR = 'ARTICLE_SAVE_ERROR';

    constructor() {
    }

    getNames() {
        return Object.getOwnPropertyNames(this);
    }
}
